#pragma once

#include <string>
#include <vector>
#include <cstdint>

namespace qwen3_tts {

// Structure to hold offline-extracted acoustic tokens and speaker embedding
struct voice_profile {
    uint32_t version;
    uint32_t sample_rate;
    uint32_t spk_dim;
    uint32_t num_frames;
    uint32_t num_quantizers;
    
    std::vector<float> speaker_embedding; // [spk_dim]
    std::vector<int32_t> audio_codes;     // [num_frames * num_quantizers]
    
    // Check if the profile is loaded and valid
    bool is_valid() const {
        return !speaker_embedding.empty() && !audio_codes.empty() && num_frames > 0;
    }
};

// Load a voice profile from a .bin file generated by extract_voice_profile.py
bool load_voice_profile(const std::string & path, voice_profile & profile);

} // namespace qwen3_tts
